name: flut1
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Your existing packages
  firebase_core: ^4.2.0
  flutter_local_notifications: ^19.5.0

  # --- ADD THESE PACKAGES ---
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_messaging: ^16.0.3
  provider: ^6.1.2 
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  cloud_functions: ^6.0.3
  # --------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true